/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/accessibility`; params?: Router.UnknownInputParams; } | { pathname: `/ar-navigation`; params?: Router.UnknownInputParams; } | { pathname: `/current-destination-details`; params?: Router.UnknownInputParams; } | { pathname: `/current-destination-select`; params?: Router.UnknownInputParams; } | { pathname: `/destination-details`; params?: Router.UnknownInputParams; } | { pathname: `/destination-select`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/accessibility`; params?: Router.UnknownOutputParams; } | { pathname: `/ar-navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/current-destination-details`; params?: Router.UnknownOutputParams; } | { pathname: `/current-destination-select`; params?: Router.UnknownOutputParams; } | { pathname: `/destination-details`; params?: Router.UnknownOutputParams; } | { pathname: `/destination-select`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/accessibility${`?${string}` | `#${string}` | ''}` | `/ar-navigation${`?${string}` | `#${string}` | ''}` | `/current-destination-details${`?${string}` | `#${string}` | ''}` | `/current-destination-select${`?${string}` | `#${string}` | ''}` | `/destination-details${`?${string}` | `#${string}` | ''}` | `/destination-select${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/accessibility`; params?: Router.UnknownInputParams; } | { pathname: `/ar-navigation`; params?: Router.UnknownInputParams; } | { pathname: `/current-destination-details`; params?: Router.UnknownInputParams; } | { pathname: `/current-destination-select`; params?: Router.UnknownInputParams; } | { pathname: `/destination-details`; params?: Router.UnknownInputParams; } | { pathname: `/destination-select`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
